author:
    first_name: Sacha 
    second_name: Schutz
    email: sacha@labsquare.org
institut:
    name: "Gustave roussy"
    url:  "https://www.gustaveroussy.fr/"

annotation:
  hg19Size: "hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes"
  refGene: "hgdownload.cse.ucsc.edu/goldenPath/hg19/database/refGene.txt.gz"


features: features/features_exon_intron.bed
basedir: /home/bioinfo/Dev/gustaveRoussy/datatest 
resultdir: /home/bioinfo/Dev/gustaveRoussy/datatest/results




samples:
    - Bone 
