author:
    first_name: Sacha 
    second_name: Schutz
    email: sacha@labsquare.org
institut:
    name: "Gustave roussy"
    url:  "https://www.gustaveroussy.fr/"


features: features/features2.bed 
basedir: /home/bioinfo/Dev/gustaveRoussy/datatest 
resultdir: /home/bioinfo/Dev/gustaveRoussy/datatest/results

wgs_variation_limit: 10  
wgs_peaks_limit: 20 


